### ISSUE TITLE
Example social-network issue of `gitlab.com/webridge-git/api` missing.

### ISSUE THREAD

**Issue by leopku** [web-ridge/gqlgen-sqlboiler#10]
1. clone this repo
2. run `cd example/social-network && go run convert_plugin.go`
3. step 2 would throw message followed
```
go: gitlab.com/webridge-git/api@v0.0.0-20181123203207-501884b46b27: reading https://goproxy.cn/gitlab.com/webridge-git/api/@v/v0.0.0-20181123203207-501884b46b27.mod: 404 Not Found
```

**Comment by RichardLindhout** [comment]
Yes that's right thats a private repo but is open sourced here https://github.com/web-ridge/utils-go/api you can send PR. Don't have time a.t.m. to fix this ;)

**Comment by RichardLindhout** [comment]
Fixed in: https://github.com/web-ridge/gqlgen-sqlboiler/commit/0c95b5d41c2cbec177f52b6231ef10ff8a3e69a7
