### ISSUE TITLE
Unknown revision github.com/gertd/go-pluralize@v0.1.4

### ISSUE THREAD

**Issue by troian** [web-ridge/gqlgen-sqlboiler#11]
It looks like there is a typo in `go.mod` as `v0.1.2` is the latest published version of github.com/gertd/go-pluralize

**Comment by RichardLindhout** [comment]
Wutt, looking into it 👍 

I've been fighting with go modules quite a bit lately but nothing with go-pluralize.

**Comment by RichardLindhout** [comment]
When I run go mod tidy it just sets go-pluralize 0.1.4 there. I don't know where it comes from.

**Comment by RichardLindhout** [comment]
https://pkg.go.dev/github.com/gertd/go-pluralize@v0.1.4?tab=doc

Go mod seems to keep a cache to this website which is really really annoying.
It also keeps references to an old version to this library so I decided to move all my files to the root instead of folders to fix that.

**Comment by RichardLindhout** [comment]
So if a library maintainer add a library 1 time it will be cached forever and we can't control the website. 

![Schermafbeelding 2020-05-07 om 21 11 28](https://user-images.githubusercontent.com/6492229/81335126-6532fd00-90a7-11ea-9ef1-1d6f8e6b3018.png)

**Comment by RichardLindhout** [comment]
I think that the repository history has been rewritten or something like that based on the https://github.com/gertd/go-pluralize/issues/8 issue.

@gertd Maybe the library should be changed to 0.1.4 to fix this issue because the pgk.go.dev website will keep this version forever.

**Comment by RichardLindhout** [comment]
I did have the same problem with https://pkg.go.dev/mod/github.com/web-ridge/gqlgen-sqlboiler/boiler@v0.0.0-20200424102639-0c95b5d41c2c. I can not refresh the website or something it's really really annoying.

**Comment by RichardLindhout** [comment]
I've posted a question about this on Stackoverflow too since I have a lot of issues with gomodules: https://stackoverflow.com/questions/61666341/disable-go-modules-caching-via-pkg-go-dev.

**Comment by RichardLindhout** [comment]
@troian Going to v2.0.2 should fix this issue!

**Comment by RichardLindhout** [comment]
![tenor](https://user-images.githubusercontent.com/6492229/81338957-be059400-90ad-11ea-8a05-93f0a57f0704.gif)

**Comment by troian** [comment]
Cheers

**Comment by RichardLindhout** [comment]
Let me know if I can close this issue!

**Comment by troian** [comment]
With fork it is good now
