### ISSUE TITLE
data assignment is ignoring cases with string type

### ISSUE THREAD

**Issue by troian** [web-ridge/gqlgen-sqlboiler#12]
In some cases function itself assigned instead of its result.
In other cases it just inserts coma
Some referenced functions do not actually exist in `boilergql` package

We have also failed some difficulties with referencing ID type. For some reason `gqlgen-sqlboiler` generates it as `uint` even though in models generated by `sqlboiler` it definitely specified as `string`
Samples of the issue
<img width="547" alt="Screen Shot 2020-05-06 at 7 54 47 PM" src="https://user-images.githubusercontent.com/2477474/81337907-c6dc7280-9079-11ea-97ad-83ce7f504e83.png">
<img width="773" alt="Screen Shot 2020-05-06 at 7 50 46 PM" src="https://user-images.githubusercontent.com/2477474/81337909-c6dc7280-9079-11ea-9010-2ddbdccead18.png">

**Comment by RichardLindhout** [comment]
It could be that indeed function does not exist in boilergql please add a PR for missing ones!

Ah in my use case we don't have string id in database. Are you using UUID as id? 

I'm generating ID's for gglgen to keep all ID's unique for Relay.dev based on uints, but that's not needed in your use case I think. I'll try to look into it as soon as possible.

It could simplify a lot of code if you use string id's!

**Comment by RichardLindhout** [comment]
It could help me a lot if you could send me a part of your database scheme or SQL with a reproduction so I could add it to https://github.com/web-ridge/gqlgen-sqlboiler-examples so your use keeps working with other releases too :)

**Comment by troian** [comment]
I can share SQL schema to reproduce the issue but would like to not publish it

**Comment by RichardLindhout** [comment]
Ok no problem I am changing existing schema to string ids to test use-case!

**Comment by RichardLindhout** [comment]
I have a failing reproduction repository: https://github.com/web-ridge/gqlgen-sqlboiler-examples/tree/master/issue-12-string-ids.

**Comment by troian** [comment]
It looks like exactly what we've got. Especially formatting :)

**Comment by RichardLindhout** [comment]
I'm almost done with fixes! Code is a lot cleaner when you have string id's 👍.

**Comment by troian** [comment]
Another note btw.
GraphQL has a special type ID. Is it possible to generate with it instead of string?

```GraphQL
type Comment {
  id: String!
  content: String!
  post: Post
  user: User!
  commentLikes: [CommentLike]
}
```

turns into
```GraphQL
type Comment {
  id: ID!
  content: String!
  post: Post
  user: User!
  commentLikes: [CommentLike]
}
```

**Comment by RichardLindhout** [comment]
It should, but it has to do with string id's!

**Comment by RichardLindhout** [comment]
![Schermafbeelding 2020-05-07 om 23 13 59](https://user-images.githubusercontent.com/6492229/81345327-894b0a00-90b8-11ea-943d-15cbba3c61c2.png)
I found the bug for that. Will try to release a new version with support for string id's tomorrow!

**Comment by RichardLindhout** [comment]
> Another note btw.
> GraphQL has a special type ID. Is it possible to generate with it instead of string?
> 
> ```graphql
> type Comment {
>   id: String!
>   content: String!
>   post: Post
>   user: User!
>   commentLikes: [CommentLike]
> }
> ```
> 
> turns into
> 
> ```graphql
> type Comment {
>   id: ID!
>   content: String!
>   post: Post
>   user: User!
>   commentLikes: [CommentLike]
> }
> ```


This issue is fixed now!
https://github.com/web-ridge/sqlboiler-graphql-schema/releases

**Comment by RichardLindhout** [comment]
Ok have most of it fixed at the moment. Still looking into an edge case for batch delete!

**Comment by RichardLindhout** [comment]
Please try v2.0.5 it works now as far I can see! Let me know if you have any issues.

Also for the boilergql package please use latest commit  like https://github.com/web-ridge/utils-go/commit/d7c1f34df76959523880e7dd81c73b4bf1d17eb7


So put d7c1f34df76959523880e7dd81c73b4bf1d17eb7 in your go.mod
```
github.com/web-ridge/utils-go/boilergql d7c1f34df76959523880e7dd81c73b4bf1d17eb7
```
And run 
```
go mod tidy
```

Somehow go modules don't understand sub repositories, I need to get a better understanding of this to release these as different packages.

**Comment by RichardLindhout** [comment]
Let me know if I can close this issue!

**Comment by RichardLindhout** [comment]
Example output can be found here: https://github.com/web-ridge/gqlgen-sqlboiler-examples/blob/master/issue-12-string-ids/helpers/convert.go

**Comment by troian** [comment]
Will test in a moment. There is one more thing)
https://github.com/web-ridge/sqlboiler-graphql-schema/issues/5

**Comment by RichardLindhout** [comment]
ID filter is not working at the moment for your use-case https://github.com/web-ridge/gqlgen-sqlboiler-examples/blob/master/issue-12-string-ids/helpers/filter.go#L39

Will fix that tomorrow it's the only place I think where interfaces are used so linters are not complaining there.

**Comment by troian** [comment]
Have this error now
```
error!!
validation failed: packages.Load: resolver/resolver.go:127:30: RemovedStringID not declared by package boilergql
```

**Comment by RichardLindhout** [comment]
> Please try v2.0.5 it works now as far I can see! Let me know if you have any issues.
> 
> Also for the boilergql package please use latest commit like [web-ridge/utils-go@d7c1f34](https://github.com/web-ridge/utils-go/commit/d7c1f34df76959523880e7dd81c73b4bf1d17eb7)
> 
> So put d7c1f34df76959523880e7dd81c73b4bf1d17eb7 in your go.mod
> 
> ```
> github.com/web-ridge/utils-go/boilergql d7c1f34df76959523880e7dd81c73b4bf1d17eb7
> ```
> 
> And run
> 
> ```
> go mod tidy
> ```
> 
> Somehow go modules don't understand sub repositories, I need to get a better understanding of this to release these as different packages.

Yes please follow this go modules are not fixed for that package.

**Comment by RichardLindhout** [comment]
I'm going to sleep now since

> RemovedIDsToBoilerString

It's there: https://github.com/web-ridge/utils-go/blob/master/boilergql/convert.go#L43
:-D

**Comment by RichardLindhout** [comment]
Closed in favor of new issue: https://github.com/web-ridge/gqlgen-sqlboiler/issues/14
