### ISSUE TITLE
ambiguous use of UserIDFromContext

### ISSUE THREAD

**Issue by troian** [web-ridge/gqlgen-sqlboiler#13]
`UserIDFromContext` seems to be required with 2 different returns types:
 - string
 - null.String

Is issue coming from our schema? or it something generated inappropriately?

**Comment by troian** [comment]
<img width="753" alt="Screen Shot 2020-05-08 at 2 08 31 PM" src="https://user-images.githubusercontent.com/2477474/81435204-74608c00-9135-11ea-9390-847d419ebf26.png">
<img width="866" alt="Screen Shot 2020-05-08 at 2 08 11 PM" src="https://user-images.githubusercontent.com/2477474/81435207-74f92280-9135-11ea-9f95-28e042eb4ac7.png">

**Comment by RichardLindhout** [comment]
I think you should require user id in schema or is this not required in your case?

**Comment by RichardLindhout** [comment]
So add not nullable in your schema to the user id field

**Comment by RichardLindhout** [comment]
I add e.g. organizationid/userid to every table to simplify authorization logic. It's built in query since user can not update something outside their scope. But I think it's required for that that user ID and organization I'd are required in table

**Comment by troian** [comment]
Hm, I think it everywhere is set to NOT NULL

**Comment by troian** [comment]
Sorry, me stupid. Fixed

**Comment by RichardLindhout** [comment]
Why does sqlboiler generate a null.String for it. I think it is not set to NOT NULL

**Comment by RichardLindhout** [comment]
Ah ok! Nice! Maybe we should support it, but I rather like that required in database. But some people do not have the option to require that in an older database so I'll add in the future probably!
