### ISSUE TITLE
Generation of pagination resolver

### ISSUE THREAD

**Issue by Niich** [web-ridge/gqlgen-sqlboiler#37]
Does gqlgen-sqlboiler currently support the generation of offset pagination resolvers?

I see that sqlboiler-graphql-schema can generate a schema with offset pagination support but the resolvers are not getting created when I run convert.

I didn't see the generation of pagination resolvers on the roadmap or done, so I figured I would ask to see if I'm just missing something or if this feature is not available.

Thanks.

**Comment by RichardLindhout** [comment]
We want pagination too but via edges/connections and cursor based pagination.

https://github.com/web-ridge/gqlgen-sqlboiler/issues/6.

This is important, but I'm short on time at the moment, but I'll definitely add it later!

**Comment by RichardLindhout** [comment]
I'm slowly building this in the development branch an the moment!

**Comment by RichardLindhout** [comment]
I'm almost ready with the cursor based pagination I need to work on one issue with custom sorting and some code cleanup

https://github.com/web-ridge/gqlgen-sqlboiler-examples/blob/development/issue-6-edges-connections/resolver.go

I also need extra tests here to make it more future-proof:
https://github.com/web-ridge/gqlgen-sqlboiler-examples/blob/development/issue-6-edges-connections/resolver_test.go

**Comment by RichardLindhout** [comment]
Released in v3.0.0
