### ISSUE TITLE
Variable transformations called by convert_input.go not defined in utils-go/boilergql/v3@v3.0.0/convert.go

### ISSUE THREAD

**Issue by orible** [web-ridge/gqlgen-sqlboiler#52]
Following transformation functions not declared by package boilergql ("github.com/web-ridge/utils-go/boilergql/v3/convert.go")

Float32ToFloat64
Float64ToFloat32 
PointerFloat64ToFloat32

PointerIntToInt8
PointerIntToUint
UintToString
StringToUint
PointerStringToUint

PointerStringToNullDotJSON
PointerStringToTypesJSON
StringToTypesJSON
TypesJSONToString

Special case this one, In order to get the SQLBoiler type, null.JSON to pass the schema step, I added a condition to output the json type as a string field.

Not sure how to fix this problem, I was thinking the library could just send out the value of the json object as a string, or undefined/empty if !Valid or null (github.com/volatiletech/null/v8/json.go)

**Comment by RichardLindhout** [comment]
Hey we need to add these functions to the go utils directory only for null.Json it should generate function names per type. Why do you want to output to string and not the json itself?




![Screenshot_20210115-094057](https://user-images.githubusercontent.com/6492229/104702104-cff80600-5715-11eb-8b79-20d66161d41b.jpg)

**Comment by RichardLindhout** [comment]
In my case I want the json to be like json in graphql and not as hardcoded string + type safe or do you have really dynamic json in your db?

Otherwise I would recommend to make the type in your gqlgen schema and converting it like the image on top.

**Comment by ollexjr** [comment]
_Why do you want to output to string and not the json itself?_

Ah, I'm relatively new to graphQL, I assumed that the schema might not work with output that isn't a pre typed interface

**Comment by RichardLindhout** [comment]
We now support JSON scalars: https://github.com/web-ridge/utils-go
