### ISSUE TITLE
Enum converts in long table names won't be generated in the where filter

### ISSUE THREAD

**Issue by arjendevos** [web-ridge/gqlgen-sqlboiler#64]
The sqlboiler parser now looks for first uppercase in the enum name. This excludes support for longer table names with underscores.

So tables like
```
company_invoice
      status enum('paid', 'unpaid')
```

The plugin will only look in the company table as model but the table should be company_invoice.
This could be fixed if we compare the enums to the models & fields from sqlboiler

**Comment by RichardLindhout** [comment]
Fixed in v3.3.3
